name: ci

on:
  push:
    paths:
      - .github/workflows/custom_ci.yml
      - lib/**
      - spec/**

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.4", "2.5", "2.6", "2.7", "jruby"]
        include:
          - ruby: "2.7"
            dry_logic_from_master: "true"
            coverage: "true"
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: eregon/use-ruby-action@master
        with:
          ruby-version: ${{matrix.ruby}}
      - name: Download test reporter
        if: "matrix.coverage == 'true'"
        run: |
          mkdir -p tmp/
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
          chmod +x ./tmp/cc-test-reporter
          ./tmp/cc-test-reporter before-build
      - name: Install latest bundler
        run: |
          gem install bundler
          bundle config set without 'tools benchmarks docs'
      - name: Run all tests
        env:
          COVERAGE: ${{matrix.coverage}}
          DRY_LOGIC_FROM_MASTER: ${{matrix.dry_logic_from_master}}
        run: |
          bundle install --jobs 4 --retry 3
          bundle exec rake
      - name: Send coverage results
        if: "matrix.coverage == 'true'"
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          GIT_COMMIT_SHA: ${{github.sha}}
          GIT_BRANCH: ${{github.ref}}
          GIT_COMMITTED_AT: ${{github.event.head_commit.timestamp}}
        run: |
          GIT_BRANCH=`ruby -e "puts ENV['GITHUB_REF'].split('/', 3).last"` \
          GIT_COMMITTED_AT=`ruby -r time -e "puts Time.iso8601(ENV['GIT_COMMITTED_AT']).to_i"` \
          ./tmp/cc-test-reporter after-build
